# Generated by Django 4.1.1 on 2022-09-19 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bussiness_userbussiness_remove_user_status_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bussiness',
            table='bussiness',
        ),
        migrations.AlterModelTable(
            name='userbussiness',
            table='user_bussiness',
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('celphone', models.CharField(max_length=15)),
                ('bussiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bussiness')),
            ],
            options={
                'db_table': 'providers',
            },
        ),
    ]
