# Generated by Django 4.1.1 on 2022-09-19 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_selldetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bussiness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bussiness_id_fk', to='api.bussiness'),
        ),
    ]
