# Generated by Django 4.1.1 on 2022-09-26 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_alter_customer_bussiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbussiness',
            name='bussiness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bussiness'),
        ),
        migrations.AlterField(
            model_name='userbussiness',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
