# Generated by Django 4.1.1 on 2022-09-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_bussiness_name_alter_bussiness_nit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='celphone',
            new_name='cellphone',
        ),
    ]
