# Generated by Django 4.1.1 on 2022-09-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_celphone_customer_cellphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='celphone',
            new_name='cellphone',
        ),
    ]
